### PR TITLE
chore: deploy updated 0x dependencies and new routing fixes

### PR DESCRIPTION
**Pull request by kimpers**
# Description
Includes updates to 0x dependencies from
* 0xProject/protocol#429
* 0xProject/protocol#430
* 0xProject/Router#36

# Testing Instructions

# Checklist

-   [ ] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:**
-   [ ] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.
-   [ ] Test changes on the staging environment with [Matcha API Staging](https://api-staging.matcha.xyz).

    -   [ ] SRA/Limit orders
    -   [ ] Swap endpoints
    -   [ ] Meta transaction endpoints
    -   [ ] Depth charts

    For more information see `0x API Matcha smoke test runbook` in Quip.

### CODE REVIEW

**Comment by kimpers** [comment]
deploy staging

**Comment by kimpers** [comment]
deploy production

**Comment by kimpers** [comment]
deploy production

**Comment by kimpers** [comment]
deploy staging

**Comment by kimpers** [comment]
deploy polygon production

**Comment by kimpers** [comment]
deploy production

**Comment by kimpers** [comment]
deploy bsc production

**Comment by kimpers** [comment]
deploy avalanche

**Comment by kimpers** [comment]
deploy avalanche production

**Comment by kimpers** [comment]
deploy optimism production

**Comment by kimpers** [comment]
deploy production

**Review by dorothy-zbornak — APPROVED** [review]

**Comment by kimpers** [comment]
deploy production

**Pull request merged**
