### PR TITLE
feat: add gmx ptp biswap balancerv2batch 

### PR DESCRIPTION
**Pull request by dextracker**
# Description
Adds support for:

- Avalanche
   - gmx
   - ptp

- BSC
   - BiSwap

-  Fantom
    - Yoshi

- Mainnet
   - KyberDMM
   - BalancerV2Batch

[Protocol publish action ](https://github.com/0xProject/protocol/commit/69bafc3bcdbbb6c42a5ade3c5b3976513bdd0dd7)

# Testing Instructions

# Checklist

-   [ ] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:**
-   [ ] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.
-   [ ] Test changes on the staging environment with [Matcha API Staging](https://api-staging.matcha.xyz).

    -   [ ] SRA/Limit orders
    -   [ ] Swap endpoints
    -   [ ] Meta transaction endpoints
    -   [ ] Depth charts

    For more information see `0x API Matcha smoke test runbook` in Quip.

### CODE REVIEW

**Comment by dextracker** [comment]
deploy avalanche production

**Review by dekz — APPROVED** [review]

**Comment by dekz** [comment]
deploy avalanche production

**Comment by dekz** [comment]
deploy bsc production

**Comment by dextracker** [comment]
🎉

**Comment by dekz** [comment]
deploy ethereum production

**Comment by dekz** [comment]
deploy ethereum production

**Comment by kh-chang** [comment]
deploy fantom production

**Comment by kh-chang** [comment]
deploy fantom production

**Comment by kh-chang** [comment]
deploy fantom production

**Pull request merged**
