### PR TITLE
feat: Add support for UniswapV2 and MultiBridge

### PR DESCRIPTION
**Pull request by xianny**
# Description

Add support for UniswapV2

Using UniswapV2Router01 contract through asset-swapper.

Add `Uniswap_V2` and `Uniswap_V2_ETH` as new sources in `excludedSources` parameter. No other changes.

# Testing Instructions

Unit tests should all still work.

# Checklist

-   [x] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:** https://github.com/0xProject/website/pull/305
-   [x] Prefix PR title with `[WIP]` if necessary.
-   [x] Add tests to cover changes as needed.

### CODE REVIEW

**Comment by xianny** [comment]
deploy staging

**Comment by xianny** [comment]
deploy staging

**Comment by xianny** [comment]
deploy staging

**Comment by xianny** [comment]
it worrrkkks 🎉 

Screen Shot 2020-06-11 at 2 47 13 PM

https://staging.api.0x.org/swap/v0/quote?sellToken=MKR&sellAmount=237000000000000000&buyToken=DAI&gasPrice=5500000000&excludedSources=Kyber,Uniswap,0x,Curve_USDC_DAI_USDT,Eth2Dai,Curve_USDC_DAI,Curve_USDC_DAI_USDT_TUSD,Curve_USDC_DAI_USDT_BUSD,0x

**Comment by dekz** [comment]
`['ETH', 'DAI', 'USDC', 'LINK', 'MKR']`

We can observe a great impact (+23%) on realized price. 5% of swaps are >5bps better, 1% of swaps are > 10bps better.

image

A slight increase in revert rate (0s), though the 60-90s revert rate is improved (where we expect most fills to land).
image


An increase in response time, though take it with a grain of salt as prod has more capacity to handle the load. Something to be cautious of though, perhaps we can retire some older Curves to make space.
image

**Comment by dekz** [comment]
deploy staging

**Comment by dekz** [comment]
deploy production

**Pull request merged**
