### PR TITLE
chore: Update AssetSwapper

### PR DESCRIPTION
**Pull request by moodlezoup**
# Description

Includes the following AS changes: https://github.com/0xProject/protocol/pull/343 https://github.com/0xProject/protocol/pull/338

`transformERC20` has been updated on all chains, so it should be safe to go back to using it in AS now
# Testing Instructions

# Checklist

-   [ ] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:**
-   [ ] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.
-   [ ] Test changes on the staging environment with [Matcha API Staging](https://api-staging.matcha.xyz).

    -   [ ] SRA/Limit orders
    -   [ ] Swap endpoints
    -   [ ] Meta transaction endpoints
    -   [ ] Depth charts

    For more information see `0x API Matcha smoke test runbook` in Quip.

### CODE REVIEW

**Review by kimpers — APPROVED** [review]
Nice! 🙏

**Comment by mzhu25** [comment]
deploy bsc production

**Comment by mzhu25** [comment]
deploy polygon production

**Comment by mzhu25** [comment]
deploy production

**Pull request merged**
