### PR TITLE
fix: specify ethgasstation url

### PR DESCRIPTION
**Pull request by dekz**
# Description

# Testing Instructions

# Checklist

-   [ ] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:**
-   [ ] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.

### CODE REVIEW

**Comment by dekz** [comment]
deploy staging

**Comment by dekz** [comment]
deploy production

**Comment by dekz** [comment]
deploy staging

**Comment by opaolini** [comment]
deploy prod

**Comment by opaolini** [comment]
deploy production

**Pull request merged**
