### PR TITLE
chore: update 0x dependencies

### PR DESCRIPTION
**Pull request by kimpers**
# Description

# Testing Instructions

# Checklist

-   [ ] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:**
-   [ ] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.
-   [ ] Test changes on the staging environment with [Matcha API Staging](https://api-staging.matcha.xyz).

    -   [ ] SRA/Limit orders
    -   [ ] Swap endpoints
    -   [ ] Meta transaction endpoints
    -   [ ] Depth charts

    For more information see `0x API Matcha smoke test runbook` in Quip.

### CODE REVIEW

**Review by dekz — APPROVED** [review]

**Comment by kimpers** [comment]
yarn deploy staging

**Comment by kimpers** [comment]
deploy staging

**Comment by kimpers** [comment]
deploy avalanche production

**Comment by kimpers** [comment]
deploy production polygon

**Comment by kimpers** [comment]
deploy production ethereum

**Comment by kimpers** [comment]
deploy production

**Pull request merged**
