### PR TITLE
chore: Require `EXCLUDED_SOURCES` to be manually updated for a new chain

### PR DESCRIPTION
**Pull request by kyu-c**
# Description

* The default excluded sources is everything except `NativeSource` which is unlikely to be desired value for a new chain. 
It would be less error-prone to fail fast and require excluded sources to be manually specified for a new chain.

# Testing Instructions

# Checklist

-   [ ] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:**
-   [ ] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.
-   [ ] Test changes on the staging environment with [Matcha API Staging](https://api-staging.matcha.xyz).

    -   [ ] SRA/Limit orders
    -   [ ] Swap endpoints
    -   [ ] Meta transaction endpoints
    -   [ ] Depth charts

    For more information see `0x API Matcha smoke test runbook` in Quip.

### CODE REVIEW

**Review by idokleinman — APPROVED** [review]

**Review by dekz — APPROVED** [review]

**Comment by idokleinman** [comment]
deploy production all

**Comment by idokleinman** [comment]
deploy production goerli

**Comment by idokleinman** [comment]
deploy production fantom

**Comment by idokleinman** [comment]
deploy production all

**Pull request merged**
