### PR TITLE
fix: fixing kovan by disabling all sources except UniswapV2

### PR DESCRIPTION
**Pull request by romainbutteaud**
# Description
- protocol PR: https://github.com/0xProject/protocol/pull/14

# Testing Instructions

# Checklist

-   [ ] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:**
-   [ ] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.

### CODE REVIEW

**Review by dekz — COMMENTED** [review]
It's probably more future proof if we iterate through the ERC20BridgeSource and select only `UniswapV2` and `Native` out of it. So when a new source is added it doesn't break kovan

**Comment by romainbutteaud** [comment]
im putting this PR in [WIP] as I might have spoke too early having kovan working... 
I'm getting `Error: VM execution error.` in AssetSwapper regardless on how many sources I exclude.

**Review by DONALDSULLENDER — APPROVED** [review]

**Comment by romainbutteaud** [comment]
@dekz fixed

**Review by dekz — APPROVED** [review]

**Comment by romainbutteaud** [comment]
deploy staging

**Comment by romainbutteaud** [comment]
deploy kovan

**Comment by romainbutteaud** [comment]
deploy kovan-staging

**Comment by romainbutteaud** [comment]
deploy production

**Comment by romainbutteaud** [comment]
simbot: https://metabase.spaceship.0x.org/dashboard/139?run_id=prod-vs-staging-10-28-001

**Pull request merged**
