### PR TITLE
fix: Add /prices and /tokens mirrors to v1 endpoints

### PR DESCRIPTION
**Pull request by kimpers**
# Description
Adds v1 support for `/tokens` and `/prices`

# Testing Instructions

# Checklist

-   [ ] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:**
-   [ ] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.

### CODE REVIEW

**Comment by kimpers** [comment]
deploy staging

**Comment by xianny** [comment]
Looks fine to me!

**Review by xianny — APPROVED** [review]

**Review by dorothy-zbornak — APPROVED** [review]
:+1:

**Comment by kimpers** [comment]
deploy staging

**Comment by kimpers** [comment]
deploy production

**Pull request merged**
