### PR TITLE
feat: turn back on quote reports for firm quotes

### PR DESCRIPTION
**Pull request by steveklebanoff**
# Description

Paired with https://github.com/0xProject/0x-monorepo/pull/2696

* Turns on quote reports _only_ for RFQT firm quotes
* Quote reports are much more optimized by looking up taker amount by signature instead of orderHash ( https://github.com/0xProject/0x-monorepo/pull/2696 )

# TODO

- [x] Ensure that it is ok to deploy latest asset-swapper changes bundled with this
- [x] Pause QuoteReport job prior to deploying

# Testing Instructions

# Checklist

-   [ ] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:**
-   [ ] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.

### CODE REVIEW

**Comment by steveklebanoff** [comment]
deploy staging

**Comment by steveklebanoff** [comment]
deploy staging

**Comment by steveklebanoff** [comment]
deploy staging

**Review by feuGeneA — APPROVED** [review]
LGTM, pending re-pin to monorepo mainline (rather than PR branch).

**Comment by steveklebanoff** [comment]
@feuGeneA done: https://github.com/0xProject/0x-api/pull/349/commits/7ddef4a404f3a6d43da3e1c0aa407a5dd350b9eb

**Comment by steveklebanoff** [comment]
deploy production

**Comment by steveklebanoff** [comment]
deploy production

**Pull request merged**
