### PR TITLE
feat: compressed requests

### PR DESCRIPTION
**Pull request by dekz**
# Description
Use the following flag to enable `gzip` compressed requests. By default this is set to `false`. This requires special server support to handle compressed requests.

```
ENABLE_RPC_REQUEST_COMPRESSION=true
```

# Testing Instructions

# Checklist

-   [ ] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:**
-   [ ] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.
-   [ ] Test changes on the staging environment with [Matcha API Staging](https://api-staging.matcha.xyz).

    -   [ ] SRA/Limit orders
    -   [ ] Swap endpoints
    -   [ ] Meta transaction endpoints
    -   [ ] Depth charts

    For more information see `0x API Matcha smoke test runbook` in Quip.

### CODE REVIEW

**Review by tobernguyen — APPROVED** [review]
LGTM. Thanks for adding new metrics to monitor request payload size. Super nice! 🙏

**Review by kimpers — APPROVED** [review]
Nice!

I stumbled upon [zlib-benchmark](https://github.com/timotejroiko/zlib-benchmark) when I was looking into zlib performance. I don't think we need that library but the readme has an interesting observation
> General performance increased about 250% from node 12 to node 15.

Might be worth looking into bumping our node version since we're on 12 😂

**Comment by dekz** [comment]
@kimpers interesting, I'll check if node 15 works well 😂

**Comment by dekz** [comment]
deploy bsc production

**Comment by dekz** [comment]
deploy celo production

**Comment by dekz** [comment]
deploy optimism production

**Comment by dekz** [comment]
deploy celo production

**Pull request merged**
