### PR TITLE
fix: update asset swapper and re-enable logs

### PR DESCRIPTION
**Pull request by PirosB3**
# Description

# Testing Instructions

# Checklist

-   [ ] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:**
-   [ ] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.

### CODE REVIEW

**Comment by opaolini** [comment]
deploy staging

**Comment by opaolini** [comment]
deploy prod

**Comment by opaolini** [comment]
deploy production

**Comment by PirosB3** [comment]
deploy staging

**Review by dekz — APPROVED** [review]

**Comment by PirosB3** [comment]
deploy prod

**Pull request merged**
