### PR TITLE
fix: meta txn arbitrary tokens

### PR DESCRIPTION
**Pull request by dekz**
# Description

We only use the symbol to see if it is `ETH` 

# Testing Instructions

# Checklist

-   [ ] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:**
-   [ ] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.

### CODE REVIEW

**Review by kimpers — APPROVED** [review]
👍

**Comment by dekz** [comment]
deploy production

**Comment by romainbutteaud** [comment]
deploy staging

**Comment by romainbutteaud** [comment]
deployed to staging and production

**Pull request merged**
