### PR TITLE
feat: Curve V2, asset-swapper and contract-addresses bump

### PR DESCRIPTION
**Pull request by romainbutteaud**
# Description

- Curve V2: (asset-swapper and contract-addresses bump)

# Testing Instructions

# Checklist

-   [ ] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:**
-   [ ] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.
-   [ ] Test changes on the staging environment with [Matcha API Staging](https://api-staging.matcha.xyz).

    -   [ ] SRA/Limit orders
    -   [ ] Swap endpoints
    -   [ ] Meta transaction endpoints
    -   [ ] Depth charts

    For more information see `0x API Matcha smoke test runbook` in Quip.

### CODE REVIEW

**Review by dekz — APPROVED** [review]

**Comment by romainbutteaud** [comment]
deploy staging

**Comment by romainbutteaud** [comment]
deploy staging

**Comment by romainbutteaud** [comment]
deploy production

**Comment by romainbutteaud** [comment]
deploy staging polygon

**Comment by romainbutteaud** [comment]
deploy polygon production

**Pull request merged**
