### PR TITLE
fix: fetch persistent orders

### PR DESCRIPTION
**Pull request by xianny**
# Description

This PR converts the query param from string to boolean and allows to fetch persistent orders properly.

# Testing Instructions

# Checklist

-   [x] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:**
-   [x] Prefix PR title with `[WIP]` if necessary.
-   [x] Add tests to cover changes as needed.
-   [ ] Test changes on the staging environment with [Matcha API Staging](https://api-staging.matcha.xyz).

    -   [ ] SRA/Limit orders
    -   [ ] Swap endpoints
    -   [ ] Meta transaction endpoints
    -   [ ] Depth charts

    For more information see `0x API Matcha smoke test runbook` in Quip.

### CODE REVIEW

**Comment by xianny** [comment]
deploy staging

**Comment by xianny** [comment]
deploy staging

**Review by kimpers — APPROVED** [review]
LGTM 👍

**Comment by xianny** [comment]
Screen Shot 2020-11-24 at 10 52 07 AM
werkz

**Comment by xianny** [comment]
deploy production

**Comment by kimpers** [comment]
deploy production

**Pull request merged**
