### PR TITLE
feat: asset-swapper bump (including Curve metapools)

### PR DESCRIPTION
**Pull request by romainbutteaud**
# Description

# Testing Instructions

# Checklist

-   [ ] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:**
-   [ ] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.

### CODE REVIEW

**Comment by romainbutteaud** [comment]
deploy staging

**Comment by romainbutteaud** [comment]
Simbot on basic tokens: https://metabase.spaceship.0x.org/dashboard/139?run_id=curl-well-made-representative&adjusted_amount_bought_win_tolerance__bps_=0.5

Simbot on extended tokens: https://metabase.spaceship.0x.org/dashboard/139?run_id=distribute-productive-son&adjusted_amount_bought_win_tolerance__bps_=0.5
`Token list for this run (17): ETH,IMBTC,EDC,YUSD,UNI,USDN,AMPL,RSR,SNX,DUSD,DAI,MUSD,PAX,TBTC,USDT,TUSD,USDC`

**Comment by romainbutteaud** [comment]
deploy production

**Comment by kimpers** [comment]
deploy staging

**Pull request merged**
